name             'devenv'
maintainer       'Yusuke Murata'
maintainer_email 'info@muratayusuke.com'
license          'All rights reserved'
description      'Set up development environment'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
depends 'docker'
depends 'git'
depends 'global'
depends 'tmux'
depends 'ncftp'
depends 'tig'
depends 'updatedb'
depends 'the_silver_searcher'
depends 'ruby_build'
depends 'rbenv'
